(require 'repository-root)
;;; 使う分だけ加えてください
(add-to-list 'repository-root-matchers repository-root-matcher/git)
(add-to-list 'repository-root-matchers repository-root-matcher/bzr)
(add-to-list 'repository-root-matchers repository-root-matcher/svn)
(add-to-list 'repository-root-matchers repository-root-matcher/hg)
(add-to-list 'repository-root-matchers repository-root-matcher/cvs)
;; (add-to-list 'repository-root-matchers repository-root-matcher/src)
;; (add-to-list 'repository-root-matchers repository-root-matcher/arch)
;; (add-to-list 'repository-root-matchers repository-root-matcher/git-submodules)
;; (add-to-list 'repository-root-matchers repository-root-matcher/ignore)
;; (add-to-list 'repository-root-matchers repository-root-matcher/autoconf)
;; (add-to-list 'repository-root-matchers repository-root-matcher/darcs)
;; (add-to-list 'repository-root-matchers repository-root-matcher/debian)
;; (add-to-list 'repository-root-matchers repository-root-matcher/kernel)
;; (add-to-list 'repository-root-matchers repository-root-matcher/bk)
