(require 'twittering-mode)
(setq twittering-use-master-password t)
(setq twittering-private-info-file "~/.emacs.d/gpgs/twittering-mode.gpg")
(setq twittering-status-format "%i %s %p: %t")
(setq twittering-retweet-format "QT: @%s %t")
(setq twittering-timer-interval 60)
(setq twittering-default-show-replied-tweets t)
(setq twittering-use-native-retweet t)
; (setq twittering-jojo-mode t)
