(defun elixir-mode-hooks ()
  (define-key elixir-mode-map (kbd "C-9") 'quick-toggle-buffer)
  (set (make-local-variable 'quick-toggle-mappings)
       '(("lib/\\(.*\\).ex" . "test/\\1_test.exs")
         ("test/\\(.*\\)_test.exs" . "lib/\\1.ex")
         ("\\([^/]*\\).ex" . "\\1_test.exs")
         ("\\([^/]*\\)_test.exs" . "\\1.ex"))))
(add-hook 'elixir-mode-hook 'elixir-mode-hooks)
